// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArceOfv0mZJQlP9krBHpyIh--ffiG3SYA',
    appId: '1:40282379478:web:60501c9047dee57e57e577',
    messagingSenderId: '40282379478',
    projectId: 'mobile-firebase-629c5',
    authDomain: 'mobile-firebase-629c5.firebaseapp.com',
    databaseURL: 'https://mobile-firebase-629c5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-firebase-629c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDictf7j05XkP_pyRhpcNOFWbdp7btAvLs',
    appId: '1:40282379478:android:a98d3093f69e8a6c57e577',
    messagingSenderId: '40282379478',
    projectId: 'mobile-firebase-629c5',
    databaseURL: 'https://mobile-firebase-629c5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-firebase-629c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAJsWhK3ZNusQUnFJN0MpAS4SKPkyHzc',
    appId: '1:40282379478:ios:7bc6573369447fd657e577',
    messagingSenderId: '40282379478',
    projectId: 'mobile-firebase-629c5',
    databaseURL: 'https://mobile-firebase-629c5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-firebase-629c5.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEAJsWhK3ZNusQUnFJN0MpAS4SKPkyHzc',
    appId: '1:40282379478:ios:7bc6573369447fd657e577',
    messagingSenderId: '40282379478',
    projectId: 'mobile-firebase-629c5',
    databaseURL: 'https://mobile-firebase-629c5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-firebase-629c5.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArceOfv0mZJQlP9krBHpyIh--ffiG3SYA',
    appId: '1:40282379478:web:da98a5f02b8f929957e577',
    messagingSenderId: '40282379478',
    projectId: 'mobile-firebase-629c5',
    authDomain: 'mobile-firebase-629c5.firebaseapp.com',
    databaseURL: 'https://mobile-firebase-629c5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-firebase-629c5.firebasestorage.app',
  );
}